services:
  - type: web
    name: pizza-store-backend
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        scope: config
        value: 10000
