// jest-dom adds custom jest matchers for asserting on DOM nodes.
// allows you to do things like:
// expect(element).toHaveTextContent(/react/i)
// learn more: https://github.com/testing-library/jest-dom
import '@testing-library/jest-dom';

const originalError = console.error;

console.error = (...args) => {
  // Suppress specific React act() warnings and unmount TypeErrors generated by our mocks
  if (
    /Warning: An update to.*inside a test was not wrapped in act/.test(args[0]) ||
    /TypeError: Cannot read properties of undefined \(reading 'data'\)/.test(args[0]) ||
    /Warning: ReactDOM.render is no longer supported in React 18/.test(args[0])
  ) {
    return;
  }
  originalError(...args);
};
